
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "http" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."abstract" (
    "id" integer NOT NULL,
    "pubmed" integer,
    "abstract" "text"
);

ALTER TABLE "public"."abstract" OWNER TO "postgres";

ALTER TABLE "public"."abstract" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."abstract_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."article" (
    "id" integer NOT NULL,
    "pubmed" integer,
    "title" "text",
    "abstract" integer,
    "journal" integer,
    "volume" character varying,
    "issue" character varying,
    "pages" character varying,
    "doi" character varying,
    "authors" "json"[],
    "auid" "json",
    "keywords" "json",
    "mesh" "json",
    "received_date" timestamp without time zone,
    "grant_number" character varying,
    "pdf_url" character varying
);

ALTER TABLE "public"."article" OWNER TO "postgres";

ALTER TABLE "public"."article" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."article_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."journal" (
    "id" integer NOT NULL,
    "journal" character varying,
    "full_name" character varying,
    "country" character varying,
    "nlm_unique_id" character varying,
    "issn_linking" character varying
);

ALTER TABLE "public"."journal" OWNER TO "postgres";

ALTER TABLE "public"."journal" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."journal_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."reference" (
    "id" bigint NOT NULL,
    "article" integer,
    "reference" character varying,
    "ref_pmid" integer,
    "ref_pmc" character varying,
    "ref_doi" character varying,
    "ref_ids" "json"
);

ALTER TABLE "public"."reference" OWNER TO "postgres";

ALTER TABLE "public"."reference" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."reference_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."abstract"
    ADD CONSTRAINT "abstract_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."article"
    ADD CONSTRAINT "article_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."article"
    ADD CONSTRAINT "article_pubmed_key" UNIQUE ("pubmed");

ALTER TABLE ONLY "public"."journal"
    ADD CONSTRAINT "journal_journal_key" UNIQUE ("journal");

ALTER TABLE ONLY "public"."journal"
    ADD CONSTRAINT "journal_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."reference"
    ADD CONSTRAINT "reference_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."article"
    ADD CONSTRAINT "article_abstract_fkey" FOREIGN KEY ("abstract") REFERENCES "public"."abstract"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."article"
    ADD CONSTRAINT "article_journal_fkey" FOREIGN KEY ("journal") REFERENCES "public"."journal"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."reference"
    ADD CONSTRAINT "reference_article_fkey" FOREIGN KEY ("article") REFERENCES "public"."article"("pubmed");

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."abstract" TO "anon";
GRANT ALL ON TABLE "public"."abstract" TO "authenticated";
GRANT ALL ON TABLE "public"."abstract" TO "service_role";

GRANT ALL ON SEQUENCE "public"."abstract_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."abstract_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."abstract_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."article" TO "anon";
GRANT ALL ON TABLE "public"."article" TO "authenticated";
GRANT ALL ON TABLE "public"."article" TO "service_role";

GRANT ALL ON SEQUENCE "public"."article_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."article_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."article_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."journal" TO "anon";
GRANT ALL ON TABLE "public"."journal" TO "authenticated";
GRANT ALL ON TABLE "public"."journal" TO "service_role";

GRANT ALL ON SEQUENCE "public"."journal_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."journal_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."journal_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."reference" TO "anon";
GRANT ALL ON TABLE "public"."reference" TO "authenticated";
GRANT ALL ON TABLE "public"."reference" TO "service_role";

GRANT ALL ON SEQUENCE "public"."reference_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."reference_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."reference_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
